// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Carousel {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ItemViewController")]
	public partial class ItemViewController {
		
		private MonoTouch.UIKit.UIButton __mt_btnClickMe;
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("btnClickMe_Click:")]
		partial void btnClickMe_Click (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Connect("btnClickMe")]
		private MonoTouch.UIKit.UIButton btnClickMe {
			get {
				this.__mt_btnClickMe = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnClickMe")));
				return this.__mt_btnClickMe;
			}
			set {
				this.__mt_btnClickMe = value;
				this.SetNativeField("btnClickMe", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
	}
}
